name: form_test
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: szepi <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha
  angular_forms: ^2.1.4

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
